version: '3.9'
services:
  todo:
    build:
      context: C:\Users\burak\GolangWorkSpace\GolangAppX
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_DRIVER: postgres
      DB_USER: postgres
      DB_PASSWORD: 3g1avcs7r
      DB_NAME: golangapp
      DB_PORT: 5432
    depends_on:
      - db
      - kafka
      - zookeeper
      - redis
    networks:
      - app_network
  authorize:
    build:
      context: C:\Users\burak\GolangWorkSpace\golangappAuth
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      DB_HOST: db
      DB_DRIVER: postgres
      DB_USER: postgres
      DB_PASSWORD: 3g1avcs7r
      DB_NAME: golangapp
      DB_PORT: 5432
    depends_on:
      - db
      - kafka
      - zookeeper
      - redis
    networks:
      - app_network
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3g1avcs7r
      POSTGRES_DB: golangapp
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - '5432:5432'
    networks:
      - app_network
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    networks:
      - app_network
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_ADVERTISED_HOST_NAME: zookeeper
    networks:
      - app_network
  notifications:
    build:
      context: C:\Users\burak\GolangWorkSpace\golangappNotifications
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - zookeeper
      - db
      - kafka
      - redis
    networks:
      - app_network
  redis:
    image: redis
    ports:
      - '6379:6379'
    environment:
      REDIS_HOST: redis
      DB_HOST: db
    depends_on:
      - db
    networks:
      - app_network
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - app_network
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - '9000:9000'
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
      - db
    networks:
      - app_network
networks:
  app_network:
    driver: bridge