name: golangci-lint
on:
  push:
    branches:
      - main
      - dev
      - refactor
  pull_request:
    branches:
      - main
      - dev
      - refactor
jobs:
  golangci:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.45.2
          # I had to add this because golangci-lint has bug with unused error check.
          # See: https://github.com/golangci/golangci-lint/issues/1517 https://github.com/golangci/golangci-lint/issues/1379
          args: --disable structcheck 